version: "3.8"

services:
    rarible-service:
      build:
       context: .
       dockerfile: Dockerfile
      container_name: rarible-integration
      ports:
        - "8080:8080"
      env_file:
        - ./.env