apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rarible-integration.fullname" . }}
  labels:
    {{- include "rarible-integration.labels" . | nindent 4 }}
data:
  app.yaml: |
    service:
      name: {{ .Values.config.serviceName | quote }}
      environment: {{ .Values.config.environment | quote }}

    server:
      port: {{ .Values.config.server.port }}
      timeout:
        router: {{ .Values.config.server.timeoutRouter | quote }}
        write: {{ .Values.config.server.writeTimeout | quote }}
        idle: {{ .Values.config.server.idleTimeout | quote }}
      cors:
        maxAge: {{ .Values.config.server.maxAge }}
        allowCredentials: {{ .Values.config.server.allowCredentials }}

    httpClient:
      timeout: {{ .Values.config.httpClient.timeout | quote }}

    rarible:
      urls:
        rarities: {{ .Values.config.rarible.urls.rarities | quote }}
        ownership: {{ .Values.config.rarible.urls.ownership | quote }}

    logger:
      level: {{ .Values.config.logger.level | quote }}
      format: {{ .Values.config.logger.format | quote }}
      withSource: {{ .Values.config.logger.withSource }}

  {{- if eq .Values.config.environment "development" }}
  dev-overrides.yaml: |
    logger:
      level: "debug"
      withSource: true
  {{- end }}

  {{- if eq .Values.config.environment "production" }}
  prod-overrides.yaml: |
    logger:
      level: "info"
      withSource: false
  {{- end }}