apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rarible-integration.fullname" . }}
  labels:
    {{- include "rarible-integration.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  rarible-api-secret: {{ .Values.secrets.rarible.apiSecret | b64enc }}